name: DiscordWebhook
version: 1.0.0
description: This plugin sends a message to a Discord Webhook
author: Dams
website: https://github.com/Dams2018/DiscordTeemHook
main: newhook.dams.discordwebhook.Webhook
commands:
 webhook:
   description: Main command
   usage: Use /webhook help